# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    hello
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |data|
    puts("___CLEAN GRADLE__")
    gradle(task: "clean")

    puts("___BUILD STAGING DEBUG APK__")
    gradle(task: "assemble",
           flavor: "staging",
           build_type: "Debug")

    puts("___DEPLOY TO CRASHLYTICS BETA__")
    crashlytics(api_token: data[:api_token],
                build_secret: data[:build_secret],
                emails: data[:qa_emails],
                notes: data[:message])
  end
end


