# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    hello
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    puts("___CLEAN GRADLE__")
    gradle(task: "clean")

    puts("___BUILD STAGING DEBUG APK__")
    gradle(task: "assemble",
           flavor: "staging",
           build_type: "Debug")

    puts("___DEPLOY TO CRASHLYTICS BETA__")
    crashlytics(api_token: "731ae80443a5d1005298e4d8934ce1bc9b4de457",
                build_secret: "73f66530d9528c3803ac54856093109a33d9cac267fc34e6f60afb928a29b22a",
                emails: "doan.van.toan@sun-asterisk.com, chu.thanh.hung@sun-asterisk.com",
                notes: "Deploy by circle ci the 2nd time")
  end
end


